before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler
language: java
script:
  - mvn clean install -Djava.awt.headless=true -P protobuf
notifications:
  email:
    recipients:
      - jeo-dev@googlegroups.com
    on_success: change
    on_failure: always
