before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler

addons:
  postgresql: "9.3"

services:
  - mongodb

before_script:
  - psql -c 'create database jeo' -U postgres
  - psql -c 'create extension postgis' -U postgres jeo

language: java
script:
  - mvn clean install -Djava.awt.headless=true -P protobuf
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  email:
    recipients:
      - jeo-dev@googlegroups.com
    on_success: change
    on_failure: always

