before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y protobuf-compiler
  - git clone -b travis `git config --get remote.origin.url` target/travis

branches:
  except:
    - travis

addons:
  postgresql: "9.3"

services:
  - mongodb

before_script:
  - psql -c 'create database jeo' -U postgres
  - psql -c 'create extension postgis' -U postgres jeo

language: java

script:
  - mvn install -Djava.awt.headless=true -P protobuf

after_success:
  - if [[ "$JAVA_HOME" == *"java-7-openjdk"* ]]; then mvn deploy -DskipTests --settings target/travis/settings.xml; fi

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

notifications:
  email:
    recipients:
      - jeo-dev@googlegroups.com
    on_success: change
    on_failure: always

env:
  global:
    - secure: "V/bzSLcg07nvbUvHyDpoxo75SQpqblD3VYzHReyFPusPAzaO1fhNlAfvAgvhH8lo43VMiQI7rx7lw7/N/M7BnTPc/IuPh/ROZDG4PdAGOiYsmNuRwEVNWZ1M2iykEGTeXmPdI7Una0SRNGoo3kCYHEiYXxreSC3/Abnq3usnktw="
    - secure: "ffmKckmzq/rsMiph2sUqVIExDG9EtRxVXFcJuJrfkNEodQEQs3SpXbLt7AnVtbu+fzz62kkWO4lrdWJadmH6ew4zHhGHAB0SauneaPgQwkwetM21U79VJkik/LPIdEABw00DFpsYrnYnpA1t8+2oTqhsAQiAed1GiLMz1hl3kiM="
